### ISSUE TITLE
Improve input box styling

### ISSUE THREAD

**Issue by GarySiu** [yxorp/Spotipare#5]
Told you they were an abomination ;)

https://www.reddit.com/r/spotify/comments/7x4zop/an_app_i_made_that_lets_you_find_songs_in_common/du60xs1/

**Comment by yxorp** [comment]
@GarySiu This was fixed in 4dc916f

**Comment by GarySiu** [comment]
They are slightly less bad but they still look like buttons and aren't stylistically great. I think it could be better.

**Comment by yxorp** [comment]
You could fix them up if you'd like

**Comment by GarySiu** [comment]
#11 Over to you

**Comment by yxorp** [comment]
Closing because 0315089
